"use client";
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, Star } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useRefresh } from '@/lib/use-refresh';
import { errorMessage, paymentTotal } from '@/lib/validation';
import { money } from '@/lib/constants';
import { Logo } from '@/components/logo';
import { StatusPill } from '@/components/status-pill';
type Engagement={id:string;customer_id:string;provider_id:string;status:string;payment_sent:boolean;payment_received:boolean;pricing_type:string;agreed_amount_tzs:number;billable_minutes:number|null;time_approved:boolean;total_amount_tzs:number|null;customer:{full_name:string}|null;provider:{full_name:string}|null};
export default function PaymentPage(){
 const {engagementId}=useParams<{engagementId:string}>();const supabase=createClient();const router=useRouter();const [me,setMe]=useState('');const [eng,setEng]=useState<Engagement|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [rating,setRating]=useState(5);const [comment,setComment]=useState('');const [proposedMinutes,setProposedMinutes]=useState(60);
 const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}setMe(user.id);const {data,error}=await supabase.from('engagements').select('id,customer_id,provider_id,status,payment_sent,payment_received,pricing_type,agreed_amount_tzs,billable_minutes,time_approved,total_amount_tzs,customer:profiles!engagements_customer_id_fkey(full_name),provider:profiles!engagements_provider_id_fkey(full_name)').eq('id',engagementId).single();if(error)throw new Error('Could not load this payment record. Check access and database setup.');setEng(data as unknown as Engagement);const {data:r,error:re}=await supabase.from('reviews').select('id').eq('engagement_id',engagementId).maybeSingle();if(re)throw re;setDone(Boolean(r));},[engagementId,router,supabase]);useRefresh(load,setError,5000);
 useEffect(()=>{setProposedMinutes(eng?.billable_minutes??60);},[eng?.billable_minutes]);
 async function action(name:string,extra:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{const {error}=await supabase.rpc(name,{p_engagement_id:engagementId,...extra});if(error)throw error;await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 function propose(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);void action('propose_billable_time',{p_minutes:Number(fd.get('minutes'))});}
 if(!eng)return <main className="shell hero"><div className="card"><p role={error?'alert':'status'}>{error||'Loading payment record…'}</p><button className="btn btn-ghost" onClick={()=>router.push('/dashboard')}>Back to dashboard</button></div></main>;
 const customer=me===eng.customer_id;const hourly=eng.pricing_type==='hourly';const ready=!hourly||(eng.billable_minutes!==null&&eng.time_approved);
 return <main className="shell dashboard"><header className="topbar"><Logo/><button className="btn btn-ghost" onClick={()=>router.push(`/match/${eng.id}`)}><ArrowLeft size={16}/>Match</button></header><div className="dash-head"><div><StatusPill status={eng.status}/><h1>{eng.total_amount_tzs!==null?money(eng.total_amount_tzs):'Let’s agree the bill.'}</h1><p className="muted">{hourly?`${money(eng.agreed_amount_tzs)} per hour${eng.billable_minutes!==null?` × ${eng.billable_minutes} minutes`:''}`:'Fixed-price agreement'}{hourly&&eng.total_amount_tzs!==null&&!eng.time_approved?' · awaiting customer approval':''}</p></div></div>{error&&<div className="error" role="alert">{error}</div>}
 <div className="dash-grid"><div>{hourly&&<section className="section card"><h2>Billable time</h2><p className="muted">The provider enters the time worked. The customer checks the time and total before confirming payment.</p>{eng.status==='completed'&&!eng.payment_sent&&!customer&&<form onSubmit={propose}><div className="field"><label htmlFor="minutes">Total minutes worked</label><input id="minutes" className="input" name="minutes" type="number" min={1} max={43200} step={1} required value={proposedMinutes} onChange={event=>setProposedMinutes(Number(event.target.value))}/></div><p className="muted">Proposed total: {money(paymentTotal(Number(eng.agreed_amount_tzs),eng.pricing_type,proposedMinutes))}</p><button className="btn btn-secondary full" disabled={busy}>Propose billable time</button></form>}{customer&&eng.status==='completed'&&eng.billable_minutes!==null&&!eng.time_approved&&<button className="btn btn-primary full" disabled={busy} onClick={()=>action('approve_billable_time',{p_minutes:eng.billable_minutes})}>Approve {eng.billable_minutes} minutes · {money(eng.total_amount_tzs)}</button>}{eng.time_approved&&<div className="success">Customer approved {eng.billable_minutes} minutes.</div>}{eng.billable_minutes===null&&<div className="notice">{eng.status==='paid'?'This older record has no recorded billable time or final total.':'Waiting for the provider to propose time after both participants confirm completion.'}</div>}</section>}
 <section className="section card"><h2>Payment confirmation</h2><p className="muted">Arrange payment directly with the provider. KaziChap records your confirmations. It does not collect, transfer or hold money in escrow.</p><div className="list-card"><div className="row between"><span>Customer marked payment sent</span><span className={`pill ${eng.payment_sent?'green':''}`}>{eng.payment_sent?'Confirmed':'Waiting'}</span></div><div className="row between"><span>Provider marked payment received</span><span className={`pill ${eng.payment_received?'green':''}`}>{eng.payment_received?'Confirmed':'Waiting'}</span></div></div>{customer&&eng.status==='completed'&&!eng.payment_sent&&ready&&<button className="btn btn-primary full" style={{marginTop:16}} disabled={busy} onClick={()=>action('mark_payment_sent',{p_expected_amount:eng.total_amount_tzs})}>I have paid {money(eng.total_amount_tzs)}</button>}{!customer&&eng.status==='completed'&&eng.payment_sent&&!eng.payment_received&&<button className="btn btn-success full" style={{marginTop:16}} disabled={busy} onClick={()=>action('mark_payment_received')}>I received {money(eng.total_amount_tzs)}</button>}{eng.status==='paid'&&<div className="success">Payment was confirmed by both participants. This record is a manual acknowledgement, not a bank receipt.</div>}{!['completed','paid'].includes(eng.status)&&<div className="notice">Payment unlocks after both participants confirm job completion.</div>}</section></div>
 <section className="card"><h2>Review the work</h2>{!customer?<p className="muted">The customer can review your work once payment is confirmed.</p>:eng.status!=='paid'?<div className="empty">Reviews unlock after payment confirmation.</div>:done?<div className="success">Your review is saved. Thank you.</div>:<><div className="stars" role="group" aria-label="Choose a rating">{[1,2,3,4,5].map(n=><button className={`star ${n<=rating?'on':''}`} key={n} aria-label={`${n} stars`} aria-pressed={n===rating} onClick={()=>setRating(n)} disabled={busy}><Star fill="currentColor"/></button>)}</div><div className="field"><label htmlFor="review">Your comments (optional)</label><textarea id="review" className="textarea" maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="How was the work, communication and punctuality?"/></div><button className="btn btn-primary full" disabled={busy} onClick={()=>action('submit_review',{p_rating:rating,p_comment:comment.trim()||null})}>Submit {rating}-star review</button></>}</section></div></main>;
}
