"use client";
import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { AuthShell } from './auth-shell';
import { errorMessage } from '@/lib/validation';
export function PasswordForm({reset=false}:{reset?:boolean}){
 const supabase=createClient();const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const fd=new FormData(event.currentTarget);setBusy(true);setError('');try{if(reset){const password=String(fd.get('password'));if(password!==fd.get('confirmation'))throw new Error('The passwords do not match.');const {error}=await supabase.auth.updateUser({password});if(error)throw error;router.replace('/dashboard');router.refresh();}else{const {error}=await supabase.auth.resetPasswordForEmail(String(fd.get('email')).trim(),{redirectTo:`${window.location.origin}/auth/confirm`});if(error)throw error;setNotice('If an account exists with that email, a password reset link has been requested. Check your inbox and spam folder.');}}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <AuthShell headline={reset?'A fresh start.':'Let’s get you back in.'} copy="Secure access to your KaziChap account."><form className="card form-card" onSubmit={submit}><h2>{reset?'Choose a new password':'Reset your password'}</h2><p>{reset?'Use at least 8 characters.':'We’ll email you a link to set a new password.'}</p>{reset?<><div className="field"><label htmlFor="new-password">New password</label><input id="new-password" name="password" className="input" type="password" minLength={8} maxLength={72} autoComplete="new-password" required/></div><div className="field"><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" name="confirmation" className="input" type="password" minLength={8} maxLength={72} autoComplete="new-password" required/></div></>:<div className="field"><label htmlFor="reset-email">Email address</label><input id="reset-email" className="input" name="email" type="email" autoComplete="email" required/></div>}{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}<button className="btn btn-primary full" disabled={busy}>{busy?'Please wait…':reset?'Save new password':'Send reset link'}</button><Link className="btn btn-ghost full" style={{marginTop:12}} href="/login">Back to login</Link></form></AuthShell>;
}
