"use client";
import { useCallback, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { MapPin, MessageCircle, Radio, Star } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { km, money } from "@/lib/constants";
import { useRefresh } from "@/lib/use-refresh";
import { errorMessage, positiveAmount } from "@/lib/validation";
import { type Profile } from "./dashboard-shell";
import { StatusPill } from "./status-pill";
import { ActionDialog } from "./action-dialog";
type Job={id:string;title:string;description:string;service_category:string;pricing_type:string;amount_tzs:number;dist_meters:number};
type Engagement={id:string;status:string;pricing_type:string;agreed_amount_tzs:number;profiles:{full_name:string}|null};
type Application={id:string;job_id:string;status:string};
export function ProviderDashboard({profile,onProfile}:{profile:Profile;onProfile:(p:Profile)=>void}){
 const supabase=createClient();const router=useRouter();const [jobs,setJobs]=useState<Job[]>([]);const [matches,setMatches]=useState<Engagement[]>([]);const [apps,setApps]=useState<Application[]>([]);
 const [error,setError]=useState("");const [dialogError,setDialogError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Job|null>(null);
 const needsVerification=['Doctor','Nurse'].includes(profile.service_category||'')&&!profile.is_verified;
 const refresh=useCallback(async()=>{const [j,e,a]=await Promise.all([
  supabase.rpc("get_nearby_jobs",{p_lat:profile.lat,p_lng:profile.lng,p_category:profile.service_category,p_radius_meters:20000}),
  supabase.from("engagements").select("id,status,pricing_type,agreed_amount_tzs,profiles!engagements_customer_id_fkey(full_name)").eq("provider_id",profile.id).order("created_at",{ascending:false}).limit(100),
  supabase.from("applications").select("id,job_id,status").eq("provider_id",profile.id).order("created_at",{ascending:false}).limit(200)
 ]);const failure=j.error||e.error||a.error;if(failure)throw failure;setJobs((j.data||[]) as Job[]);setMatches((e.data||[]) as unknown as Engagement[]);setApps((a.data||[]) as Application[]);setLoading(false);},[supabase,profile.id,profile.lat,profile.lng,profile.service_category]);useRefresh(refresh,setError);
 async function action(work:()=>Promise<void>,dialog=false){if(busy)return;setBusy(true);setError("");setDialogError("");try{await work();}catch(e){(dialog?setDialogError:setError)(errorMessage(e));}finally{setBusy(false);}}
 async function apply(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);if(!selected)return;await action(async()=>{const rate=positiveAmount(String(fd.get('rate')));if(rate===null)throw new Error('Enter a valid amount in TZS.');const {error}=await supabase.rpc('apply_to_job',{p_job_id:selected.id,p_note:String(fd.get('note')).trim(),p_rate:rate});if(error)throw error;setSelected(null);setNotice('Application sent. You can track its status below.');await refresh();},true);}
 async function chat(id:string){await action(async()=>{const {data,error}=await supabase.from('conversations').select('id').eq('engagement_id',id).single();if(error)throw error;router.push(`/chat/${data.id}`);});}
 return <><div className="dash-head"><div><div className="eyebrow"><MapPin size={13}/>{profile.area||'Your saved location'}</div><h1>Your next job starts nearby.</h1><p className="muted">{profile.service_category} · {money(profile.hourly_rate_tzs)}/hr</p><span className="pill"><Star size={13}/>{profile.review_count?`${Number(profile.rating_avg).toFixed(1)} · ${profile.review_count} reviews`:'New provider'}</span></div><button className={`btn ${profile.is_online?'btn-success':'btn-secondary'}`} disabled={busy||needsVerification} onClick={()=>action(async()=>{const next=!profile.is_online;const {error}=await supabase.rpc('set_online',{p_online:next});if(error)throw error;onProfile({...profile,is_online:next});})}><Radio size={16}/>{profile.is_online?'Online · visible':'Go online'}</button></div>
 {needsVerification&&<div className="notice">Your professional profile needs administrator verification before you can appear in discovery or accept work. Verification cannot be granted through this app.</div>}
 {error&&<div className="error" role="alert">{error}<button className="btn btn-ghost" disabled={busy} onClick={()=>action(refresh)}>Retry</button></div>}{notice&&<div className="success" role="status">{notice}</div>}
 <div className="stats-grid"><div><strong>{jobs.length}</strong><span>Nearby jobs</span></div><div><strong>{apps.filter(a=>a.status==='pending').length}</strong><span>Pending applications</span></div><div><strong>{matches.filter(e=>['accepted','in_progress'].includes(e.status)).length}</strong><span>Active matches</span></div></div>
 <div className="dash-grid"><section className="section card"><div className="section-head"><h2>Nearby open jobs</h2><span className="pill">Within 20 km</span></div><div className="list">{loading?<div className="empty" role="status">Finding nearby jobs…</div>:jobs.length?jobs.map(j=>{const app=apps.find(a=>a.job_id===j.id);return <article key={j.id} className="list-card"><div className="row between"><h3>{j.title}</h3><span className="price">{money(j.amount_tzs)} {j.pricing_type==='hourly'?'/hr':'fixed'}</span></div><span className="muted tiny">{j.service_category} · {km(j.dist_meters)} (approx.)</span><p className="muted">{j.description}</p>{app?<div className="row">Application <StatusPill status={app.status}/></div>:<button className="btn btn-primary" disabled={busy||needsVerification} onClick={()=>{setSelected(j);setDialogError('');}}>Apply for this job</button>}</article>;}):<div className="empty">{needsVerification?'Nearby work unlocks after professional verification.':'No matching jobs nearby yet. Check back soon.'}</div>}</div></section>
 <div><section className="section card"><h2>Matches & inquiries</h2><div className="list">{matches.length?matches.map(e=><article className="list-card" key={e.id}><div className="row between"><h3>{e.profiles?.full_name||'Customer'}</h3><StatusPill status={e.status}/></div><span className="price">{money(e.agreed_amount_tzs)} {e.pricing_type==='hourly'?'/hr':'fixed'}</span><div className="row"><button className="btn btn-ghost" disabled={busy} onClick={()=>chat(e.id)}><MessageCircle size={15}/>Chat</button><button className="btn btn-secondary" onClick={()=>router.push(`/match/${e.id}`)}>Open match</button></div>{e.status==='requested'&&<button className="btn btn-primary" disabled={busy||needsVerification} onClick={()=>action(async()=>{const {error}=await supabase.rpc('provider_accept_engagement',{p_engagement_id:e.id});if(error)throw error;await refresh();})}>Accept inquiry</button>}</article>):<div className="empty">Customer inquiries and accepted applications appear here.</div>}</div></section><section className="section card"><h2>Application history</h2><div className="list">{apps.length?apps.map(a=><div className="list-card" key={a.id}><div className="row between"><span>{jobs.find(j=>j.id===a.job_id)?.title||`Job ${a.job_id.slice(0,8)}`}</span><StatusPill status={a.status}/></div></div>):<p className="muted">You haven’t applied to a job yet.</p>}</div></section></div></div>
 {selected&&<ActionDialog title={`Apply: ${selected.title}`} busy={busy} onClose={()=>setSelected(null)} onSubmit={apply} submitLabel="Send application"><div className="field"><label htmlFor="application-rate">{selected.pricing_type==='hourly'?'Your hourly rate (TZS)':'Your total fixed price (TZS)'}</label><input autoFocus className="input" id="application-rate" name="rate" type="number" min={1} max={100000000} step="0.01" required defaultValue={selected.pricing_type==='fixed'?selected.amount_tzs:profile.hourly_rate_tzs||selected.amount_tzs}/></div><div className="field"><label htmlFor="application-note">Why are you a good fit?</label><textarea className="textarea" id="application-note" name="note" required maxLength={1000} placeholder="Share your availability and relevant experience."/></div>{dialogError&&<div className="error" role="alert">{dialogError}</div>}</ActionDialog>}
 </>;
}
