"use client";
import Link from 'next/link';
import { type FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AuthShell } from '@/components/auth-shell';
import { createClient } from '@/lib/supabase/client';
import { errorMessage, safeRedirect } from '@/lib/validation';
export default function LoginPage(){
 const supabase=createClient();const router=useRouter();const [email,setEmail]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const fd=new FormData(event.currentTarget);setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password:String(fd.get('password'))});if(error)throw error;const next=new URLSearchParams(window.location.search).get('next');router.replace(safeRedirect(next));router.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function resend(){if(busy)return;if(!email.trim()||!email.includes('@')){setError('Enter your email address first.');return;}setBusy(true);setError('');try{const {error}=await supabase.auth.resend({type:'signup',email:email.trim(),options:{emailRedirectTo:`${window.location.origin}/auth/confirm`}});if(error)throw error;setNotice('If your account needs confirmation, a new email has been requested. Check your inbox and spam folder.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <AuthShell headline="Welcome back." copy="Your work, conversations and next opportunity, all in one place."><form className="card form-card" onSubmit={submit}><div className="eyebrow">Your KaziChap account</div><h2 style={{marginTop:20}}>Sign in</h2><p>Pick up where you left off.</p><div className="field"><label htmlFor="login-email">Email</label><input className="input" id="login-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label htmlFor="login-password">Password</label><input className="input" id="login-password" name="password" type="password" autoComplete="current-password" required/></div><Link href="/forgot-password" className="text-link">Forgot password?</Link>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}<button className="btn btn-primary full" disabled={busy} style={{marginTop:20}}>{busy?'Please wait…':'Sign in'}</button><button type="button" className="btn btn-ghost full" style={{marginTop:10}} disabled={busy} onClick={resend}>Resend confirmation email</button><p className="muted tiny" style={{marginTop:20}}>New here? <Link className="text-link" href="/">Create an account</Link></p></form></AuthShell>;
}
