"use client";
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, CheckCircle2, MapPin, MessageCircle } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useRefresh } from '@/lib/use-refresh';
import { errorMessage } from '@/lib/validation';
import { money } from '@/lib/constants';
import { Logo } from '@/components/logo';
import { StatusPill } from '@/components/status-pill';
import { LiveMatchMap } from '@/components/live-match-map';
import { ActionDialog } from '@/components/action-dialog';
type Engagement={id:string;customer_id:string;provider_id:string;status:string;pricing_type:string;agreed_amount_tzs:number;customer_completed:boolean;provider_completed:boolean;customer:{full_name:string}|null;provider:{full_name:string}|null};
type Location={user_id:string;lat:number;lng:number;updated_at:string};
export default function MatchPage(){
 const {engagementId}=useParams<{engagementId:string}>();const router=useRouter();const supabase=createClient();
 const [me,setMe]=useState('');const [eng,setEng]=useState<Engagement|null>(null);const [locs,setLocs]=useState<Location[]>([]);const [error,setError]=useState('');const [gpsError,setGpsError]=useState('');const [busy,setBusy]=useState(false);const [sharing,setSharing]=useState(false);const [cancel,setCancel]=useState(false);const [dialogError,setDialogError]=useState('');
 const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}setMe(user.id);const {data,error}=await supabase.from('engagements').select('id,customer_id,provider_id,status,pricing_type,agreed_amount_tzs,customer_completed,provider_completed,customer:profiles!engagements_customer_id_fkey(full_name),provider:profiles!engagements_provider_id_fkey(full_name)').eq('id',engagementId).single();if(error)throw new Error('Match not found, or you do not have access.');setEng(data as unknown as Engagement);const {data:l,error:le}=await supabase.from('engagement_locations').select('user_id,lat,lng,updated_at').eq('engagement_id',engagementId);if(le)throw le;setLocs((l||[]) as Location[]);},[engagementId,router,supabase]);
 useRefresh(load,setError,5000);
 useEffect(()=>{const channel=supabase.channel(`match:${engagementId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'engagements',filter:`id=eq.${engagementId}`},()=>{void load().catch(e=>setError(errorMessage(e)));}).subscribe();return()=>{void supabase.removeChannel(channel);};},[engagementId,load,supabase]);
 const active=!!eng&&['accepted','in_progress'].includes(eng.status);
 useEffect(()=>{if(!sharing||!active)return;if(!navigator.geolocation){setGpsError('This browser does not support location sharing.');setSharing(false);return;}let disposed=false;let last=0;let sending=false;
 const id=navigator.geolocation.watchPosition(async p=>{if(disposed||sending||Date.now()-last<10000)return;last=Date.now();sending=true;try{const {error}=await supabase.rpc('upsert_engagement_location',{p_engagement_id:engagementId,p_lat:p.coords.latitude,p_lng:p.coords.longitude});if(!disposed&&error){setGpsError(error.message);setSharing(false);}}catch{if(!disposed)setGpsError('Location could not update. Check your connection.');}finally{sending=false;if(disposed)void supabase.rpc('stop_sharing_location',{p_engagement_id:engagementId}).then(()=>{},()=>{});}},e=>{if(!disposed){setGpsError(e.code===1?'Location permission was denied. Allow it in your browser settings to share.':'Location is unavailable. You can still coordinate in chat.');setSharing(false);}},{enableHighAccuracy:true,maximumAge:8000,timeout:15000});
 return()=>{disposed=true;navigator.geolocation.clearWatch(id);void supabase.rpc('stop_sharing_location',{p_engagement_id:engagementId}).then(()=>{},()=>{});};},[active,sharing,engagementId,supabase]);
 const points=useMemo(()=>active?locs.filter(l=>Date.now()-Date.parse(l.updated_at)<60000).map(l=>({user_id:l.user_id,lat:l.lat,lng:l.lng,label:l.user_id===eng?.customer_id?eng.customer?.full_name||'Customer':eng?.provider?.full_name||'Provider'})):[],[locs,eng,active]);
 async function action(name:string,dialog=false){if(busy)return;setBusy(true);setError('');setDialogError('');try{const {error}=await supabase.rpc(name,{p_engagement_id:engagementId});if(error)throw error;setCancel(false);await load();}catch(e){(dialog?setDialogError:setError)(errorMessage(e));}finally{setBusy(false);}}
 async function chat(){if(busy)return;setBusy(true);try{const {data,error}=await supabase.from('conversations').select('id').eq('engagement_id',engagementId).single();if(error)throw error;router.push(`/chat/${data.id}`);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(!eng)return <main className="shell hero"><div className="card"><p role={error?'alert':'status'}>{error||'Loading match…'}</p><button className="btn btn-ghost" onClick={()=>router.push('/dashboard')}>Back to dashboard</button></div></main>;
 const customer=me===eng.customer_id;const completed=customer?eng.customer_completed:eng.provider_completed;const steps=['requested','accepted','in_progress','completed','paid'];const index=steps.indexOf(eng.status);
 return <main className="shell dashboard"><header className="topbar"><Logo/><button className="btn btn-ghost" onClick={()=>router.push('/dashboard')}><ArrowLeft size={16}/>Dashboard</button></header><div className="dash-head"><div><div className="row"><StatusPill status={eng.status}/><span className="pill">{money(eng.agreed_amount_tzs)} {eng.pricing_type==='hourly'?'/hr':'fixed'}</span></div><h1>{customer?eng.provider?.full_name:eng.customer?.full_name}</h1><p className="muted">Your job, from first conversation to completion.</p></div></div>{error&&<div className="error" role="alert">{error}</div>}{eng.status!=='cancelled'&&<div className="status-flow">{steps.map((s,i)=><div key={s} className={`step ${i<=index?'active':''}`}>{i+1}. {s.replaceAll('_',' ')}</div>)}</div>}
 <div className="dash-grid"><section className="card map-card">{active?<LiveMatchMap points={points}/>:<div className="empty">{eng.status==='requested'?'The map unlocks after the provider accepts.':'Location sharing has ended for this match.'}</div>}<div className="map-meta"><div className="row between"><strong><MapPin size={15}/> {sharing&&active?'Sharing your location':'Location sharing is off'}</strong><span className="pill">{points.length}/2 recent positions</span></div><p className="muted tiny">Choose to share your position with the other participant while this match is active. Updates are sent at most once every 10 seconds while this page is open. Positions older than a minute are hidden.</p>{active&&<button className={`btn ${sharing?'btn-ghost':'btn-primary'}`} onClick={()=>{setGpsError('');setSharing(!sharing);}}>{sharing?'Stop sharing':'Share my live location'}</button>}{gpsError&&<div className="error" role="alert">{gpsError}</div>}</div></section>
 <section className="card"><h2>Match controls</h2><div className="list"><button className="btn btn-ghost full" onClick={chat} disabled={busy}><MessageCircle size={16}/>Open chat</button>{eng.status==='requested'&&(customer?<div className="notice">Waiting for the provider to accept your inquiry.</div>:<button className="btn btn-primary full" disabled={busy} onClick={()=>action('provider_accept_engagement')}>Accept inquiry</button>)}{eng.status==='accepted'&&<button className="btn btn-primary full" disabled={busy} onClick={()=>action('begin_engagement')}>Start job</button>}{eng.status==='in_progress'&&!completed&&<button className="btn btn-success full" disabled={busy} onClick={()=>action('confirm_completion')}><CheckCircle2 size={16}/>Confirm work completed</button>}{eng.status==='in_progress'&&completed&&<div className="success">You confirmed completion. Waiting for the other participant.</div>}{['completed','paid'].includes(eng.status)&&<button className="btn btn-primary full" onClick={()=>router.push(`/payment/${eng.id}`)}>{eng.status==='paid'?'View payment record & review':'Agree bill & confirm payment'}</button>}{['requested','accepted'].includes(eng.status)&&<button className="btn btn-ghost full" disabled={busy} onClick={()=>{setCancel(true);setDialogError('');}}>Cancel match</button>}{eng.status==='cancelled'&&<p className="muted">This match was cancelled. No payment was processed by KaziChap.</p>}</div></section></div>
 {cancel&&<ActionDialog title="Cancel this match?" busy={busy} onClose={()=>setCancel(false)} onSubmit={e=>{e.preventDefault();void action('cancel_engagement',true);}} submitLabel="Confirm cancellation"><p className="muted">This closes the match and any linked job. The conversation remains available.</p>{dialogError&&<div className="error" role="alert">{dialogError}</div>}</ActionDialog>}
 </main>;
}
