"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { LocateFixed, MapPin } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { Logo } from '@/components/logo';
import { errorMessage, validCoordinates } from '@/lib/validation';
export default function LocationPage(){
 const router=useRouter();const supabase=createClient();const [coords,setCoords]=useState<{lat:number;lng:number}|null>(null);const [area,setArea]=useState('');const [manualLat,setManualLat]=useState('');const [manualLng,setManualLng]=useState('');const [error,setError]=useState('');const [locating,setLocating]=useState(false);const [busy,setBusy]=useState(false);
 function locate(){setError('');if(!navigator.geolocation){setError('Your browser does not support location. Try a current browser.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setCoords({lat:p.coords.latitude,lng:p.coords.longitude});setLocating(false);},e=>{setLocating(false);setError(e.code===1?'Location access was denied. Use the icon next to the address bar to allow location, then try again.':e.code===3?'Location timed out. Move near a window or try your phone.':'Your location is unavailable. Check your device location settings.');},{enableHighAccuracy:true,timeout:30000,maximumAge:0});}
 function useManualLocation(){const lat=Number(manualLat);const lng=Number(manualLng);if(!validCoordinates(lat,lng)){setError('Enter a valid latitude and longitude.');return;}setCoords({lat,lng});setError('');}
 async function save(){if(busy)return;if(!coords||!validCoordinates(coords.lat,coords.lng)){setError('Capture your current location first.');return;}setBusy(true);setError('');try{const {error}=await supabase.rpc('set_my_location',{p_lat:coords.lat,p_lng:coords.lng,p_area:area.trim()||null});if(error)throw error;router.replace('/dashboard');router.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <main className="shell"><header className="topbar"><Logo/></header><section className="hero"><div className="card form-card"><div className="role-icon"><MapPin/></div><h2>Work starts nearby.</h2><p>Save your current location to find nearby jobs or providers. Discovery shows an approximate distance. During an active match, you can choose to share your live position.</p><button className="btn btn-secondary full" onClick={locate} disabled={locating||busy}><LocateFixed size={17}/>{locating?'Finding your location…':'Use my current location'}</button><div className="field" style={{marginTop:18}}><label htmlFor="area">Area / neighbourhood (optional)</label><input className="input" id="area" maxLength={120} value={area} onChange={e=>setArea(e.target.value)} placeholder="Sinza, Dar es Salaam"/></div><div className="field"><label htmlFor="manual-lat">Or enter coordinates manually</label><div style={{display:'flex',gap:8}}><input className="input" id="manual-lat" type="number" step="any" value={manualLat} onChange={e=>setManualLat(e.target.value)} placeholder="Latitude e.g. -6.7924"/><input className="input" id="manual-lng" type="number" step="any" value={manualLng} onChange={e=>setManualLng(e.target.value)} placeholder="Longitude e.g. 39.2083"/></div><button className="btn btn-secondary full" onClick={useManualLocation} disabled={busy||locating}>Use manual location</button></div>{coords&&<div className="success" role="status">Location captured. You can now continue.</div>}{error&&<div className="error" role="alert">{error}</div>}<button className="btn btn-primary full" onClick={save} disabled={busy||locating||!coords}>{busy?'Saving…':'Save and continue'}</button></div></section></main>;
}
